### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by felixmariotto** [RenaudRohlinger/three-material-editor#2]
I wanted to add your editor to my game's engine to edit materials faster, but I'm running against an error when I try to import your modules as explained in your readme : 

![Screenshot_1](https://user-images.githubusercontent.com/46470486/107366220-2a4e7180-6ade-11eb-83cb-47374e60c2ee.png)

I'm wondering why there is a reference to `process` in client code ? am I importing the wrong things ?
This the only thing I added in my code : 

```javascript
import {
  MaterialEditor,
  useEditorComposer
} from '@three-material-editor/vanilla';
```

I also get `Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools`, so I'm wondering : is using React a requirement in order to use your material editor ? Because I'm just making a game with hardly any UI, there is no point using React for me.

**Comment by RenaudRohlinger** [comment]
Process is not defined means, either way, you don't have a node server to develop (what's your local server ?) or you already have a function called process in your code.

The tool is made with react but it won't affect your work since it's automatically removed from the production (using process.env). You can also just remove the import on production.

Also, the full size of the editor with react incorporated is 140ko which should be ok for a development environment.

**Comment by felixmariotto** [comment]
I'm bundling with webpack and I use webpack-dev-server in development.
When I import your modules in my client-side app with
```js
import {
  MaterialEditor,
  useEditorComposer
} from '@three-material-editor/vanilla';
```
it's bundled and served to the client, and then when it runs `process` is not here since `process` is a nodejs module and this code is executed in the browser. I must misunderstand something obvious, sorry to be dense...

**Comment by felixmariotto** [comment]
Here is a minimal app to reproduce : https://github.com/felixmariotto/issue-material-editor

- run `npm run dev`
- browser opens on the site running the bundle
- see the errors in the console
